(define (problem q2-truck)
   (:domain q1-truck)
   (:objects truck-delivery package1 isfree bedok changi tampines)
   (:init (place bedok)
          (place changi)
          (place tampines)
          (package package1)
          (truck truck-delivery)
          (truck-at tampines)
          (inTruck isfree package1)
          (package-at package1 bedok))
   (:goal (package-at package1 changi)))