(define (problem q2-truck)
   (:domain q1-truck)
   (:objects truck-delivery package1 package2 bedok changi tampines isfree)
   (:init (place bedok)
          (place changi)
          (place tampines)
          (package package1)
          (package package2)
          (truck truck-delivery)
          (truck-at tampines)
          (inTruck isfree package1)
          (inTruck isFree package2)
          (package-at package1 bedok)
          (package-at package2 changi))
   (:goal (and(package-at package1 changi)
   (package-at package2 bedok)
   )
   ))